package recomp.codegen;

import recomp.analysis.Func;
import recomp.analysis.Image;
import recomp.mips.Decoder;
import recomp.mips.Op;

/**
	What the program itself says about where its time goes, for a layout of the native code that
	needs no run of the game (ADR-0063): written beside the generated tree as `Layout.txt`, read
	at every Dreamcast link by scripts/dc-layout.py.

	No trace, no profile: only the code's structure, the same for every build of the same disc.
	A block's weight grows by LOOP_STEP with each loop it is in (a backward branch's range in the
	original program, which is how the PlayStation's compilers and its hand-written code lay a
	loop out), up to LOOP_CAP loops; a function's local heat is its instructions so weighted, its
	GTE commands counted again (a GTE command is per-vertex work: the one sure sign of a renderer);
	its calls a frame start at one and flow down the direct call graph, each call site's own weight
	times its caller's, a few rounds over every edge, capped. A function reached only by address — a
	jump table's, a pointer's — keeps its one: the heat of its own loops is all it has.

	Integers only, so two builds of the same tree write the same file.
**/
class LayoutHints {
	static inline var LOOP_STEP = 8;
	static inline var LOOP_CAP = 3;
	static inline var GTE_WEIGHT = 16;
	static inline var CALLS_CAP = 1 << 20;
	static inline var ROUNDS = 6;

	final rows:Array<{cls:String, fn:Func, image:Image}> = [];

	public function new() {}

	public function add(cls:String, fn:Func, image:Image):Void {
		rows.push({cls: cls, fn: fn, image: image});
	}

	static function weight(depth:Int):Int {
		var w = 1;
		var d = depth < LOOP_CAP ? depth : LOOP_CAP;
		while (d > 0) { w *= LOOP_STEP; d--; }
		return w;
	}

	/** Each block's loop depth: how many backward branches' ranges hold it. */
	static function depths(fn:Func):Map<Int, Int> {
		final addrs = [for (a in fn.blocks.keys()) a];
		addrs.sort((a, b) -> a - b);
		final loops:Array<{from:Int, to:Int}> = [];
		for (a in addrs) {
			final b = fn.blocks.get(a);
			for (s in b.successors) {
				if (s <= a && fn.blocks.exists(s)) loops.push({from: s, to: b.endAddr()});
				else {}
			}
		}
		final out:Map<Int, Int> = [];
		for (a in addrs) {
			var d = 0;
			for (l in loops) if (a >= l.from && a < l.to) d++;
			out.set(a, d);
		}
		return out;
	}

	public function source():String {
		final byEntry:Map<Int, Int> = [];
		for (i in 0...rows.length) {
			if (!byEntry.exists(rows[i].fn.entry)) byEntry.set(rows[i].fn.entry, i);
			else {}
		}
		final local = [for (_ in rows) 0];
		final gte = [for (_ in rows) 0];
		final edges:Array<{from:Int, to:Int, w:Int}> = [];
		for (i in 0...rows.length) {
			final fn = rows[i].fn;
			final image = rows[i].image;
			final depth = depths(fn);
			var loc = 0;
			var g = 0;
			for (a in fn.blocks.keys()) {
				final b = fn.blocks.get(a);
				final w = weight(depth.get(a));
				loc += b.length * w;
				for (k in 0...b.length) {
					final at = a + k * 4;
					if (!image.containsWord(at)) continue;
					else {}
					if (Decoder.decode(at, image.readWord(at)).op == Op.COP2CMD) g += w;
					else {}
				}
			}
			local[i] = loc;
			gte[i] = g;
			// A call's weight is its block's: the block that holds the call instruction.
			final sites = fn.calls.concat(fn.tailCalls);
			for (c in sites) {
				if (c.indirect || c.target == 0 || !byEntry.exists(c.target)) continue;
				else {}
				var site = -1;
				for (a in fn.blocks.keys()) {
					final b = fn.blocks.get(a);
					if (c.from >= a && c.from < b.endAddr()) { site = a; break; }
					else {}
				}
				edges.push({from: i, to: byEntry.get(c.target), w: site >= 0 ? weight(depth.get(site)) : 1});
			}
		}
		// Calls a frame, relative: one each, then down the edges, a few rounds, capped.
		var calls = [for (_ in rows) 1];
		for (_ in 0...ROUNDS) {
			final next = [for (_ in rows) 1];
			for (e in edges) {
				if (e.from == e.to) continue;
				else {}
				final add = calls[e.from] >= CALLS_CAP / e.w ? CALLS_CAP : calls[e.from] * e.w;
				final sum = next[e.to] + add;
				next[e.to] = sum > CALLS_CAP || sum < 0 ? CALLS_CAP : sum;
			}
			calls = next;
		}
		final buf = new StringBuf();
		buf.add('# Generated by recompsx: the program\'s own estimate of where its time goes (ADR-0063), for\n');
		buf.add('# scripts/dc-layout.py\'s layout of the native code. No trace: loops, GTE commands and direct\n');
		buf.add('# calls only (codegen.LayoutHints). One line a function:\n');
		buf.add('# class function entry instructions local gte calls (heat = calls x (local + ${GTE_WEIGHT} gte), the reader\'s)\n');
		for (i in 0...rows.length) {
			final r = rows[i];
			buf.add('${r.cls} ${r.fn.name} ${StringTools.hex(r.fn.entry, 8)} ${r.fn.instructionCount()} ${local[i]} ${gte[i]} ${calls[i]}\n');
		}
		buf.add('# edges: caller callee weight\n');
		for (e in edges) buf.add('E ${rows[e.from].cls}.${rows[e.from].fn.name} ${rows[e.to].cls}.${rows[e.to].fn.name} ${e.w}\n');
		return buf.toString();
	}
}
