package recomp.codegen;

import recomp.config.ModConfig;
import sys.FileSystem;
import sys.io.File;

/**
	The part of a program `gen --mods` adds (ADR-0033): each mod's sources, copied beside the
	generated code under the mod's package, and `ModList`, which installs them.

	Copied rather than referenced so that a build still compiles "whatever is in the output
	directory", as every hxml here assumes; `ModList` is what keeps the mods alive through
	`-dce full`, and it is only compiled when the launcher asks for it (`-D recompsx_mods`).
**/
class ModOutput {
	/** Left in each copied mod directory, so the next `gen` knows the directory is its own. */
	static inline var MARKER = ".recompsx-mod";

	/**
		Removes the mods a previous `gen` copied here. `Program.writeTo` already removed its
		`ModList.hx` with the rest of the generated files; this is the directories beside them.
	**/
	public static function clean(dir:String):Void {
		if (!FileSystem.exists(dir)) return;
		for (name in FileSystem.readDirectory(dir)) {
			final sub = '$dir/$name';
			if (FileSystem.isDirectory(sub) && FileSystem.exists('$sub/$MARKER')) removeTree(sub);
		}
	}

	public static function write(dir:String, mods:Array<ModConfig>):Int {
		var files = 0;
		for (m in mods) {
			final target = '$dir/${m.id}';
			FileSystem.createDirectory(target);
			File.saveContent('$target/$MARKER', 'copied by recompsx gen --mods from ${m.dir}\n');
			for (rel in m.sources()) {
				final to = '$target/$rel';
				final parent = to.substr(0, to.lastIndexOf("/"));
				FileSystem.createDirectory(parent);
				File.copy('${m.dir}/$rel', to);
				files++;
			}
		}
		File.saveContent('$dir/ModList.hx', modListSource(mods));
		return files + 1;
	}

	static function modListSource(mods:Array<ModConfig>):String {
		final buf = new StringBuf();
		buf.add('// Generated by recompsx gen --mods. Do not edit: regenerate (golden rule 5).\n\n');
		buf.add('/**\n\tThe mods this build carries (ADR-0033):\n');
		for (m in mods) buf.add('\t- ${m.describe()}\n');
		buf.add('\n\tInstalled by the launcher before the game\'s first instruction, and only in a\n');
		buf.add('\tbuild with `-D recompsx_mods`.\n**/\n');
		buf.add('class ModList {\n');
		buf.add('\tpublic static function install():Void {\n');
		// One heap for all of them: in the mods' own memory past 2 MB, as much as the largest
		// request, unless a manifest put it in guest RAM (the first to do so decides).
		var inRam:Null<ModConfig> = null;
		var memory = 0;
		for (m in mods) {
			if (inRam == null && m.heapAddr != null) inRam = m;
			if (m.memory > memory) memory = m.memory;
		}
		if (inRam != null) buf.add('\t\tmod.ModHost.heap(${hex(inRam.heapAddr)}, ${inRam.heapSize});\n');
		else buf.add('\t\tmod.ModHost.expansion(${memory > 0 ? memory : ModConfig.DEFAULT_MEMORY});\n');
		final seen:Map<Int, Bool> = [];
		for (m in mods) {
			for (h in m.hooks) {
				if (!seen.exists(h.addr)) buf.add('\t\tmod.ModHost.declare(${hex(h.addr)});\n');
				seen.set(h.addr, true);
			}
		}
		for (m in mods) buf.add('\t\t${m.entry}.install();\n');
		buf.add('\t}\n}\n');
		return buf.toString();
	}

	static function hex(v:Int):String return "0x" + StringTools.hex(v, 8).toLowerCase();

	static function removeTree(path:String):Void {
		for (name in FileSystem.readDirectory(path)) {
			final p = '$path/$name';
			if (FileSystem.isDirectory(p)) removeTree(p);
			else FileSystem.deleteFile(p);
		}
		FileSystem.deleteDirectory(path);
	}
}
